name: sync_once
description: The function will be called only once.

version: 1.0.2
repository: https://github.com/ryicoh/sync_once

environment:
  sdk: '>=2.14.2 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.18.2

dependencies: 
  synchronized: ^3.0.0
