name: sync_once
description: A simple command-line application.
version: 1.0.0
repository: https://github.com/ryicoh/sync_once

environment:
  sdk: '>=2.14.2 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
dependencies: 
  synchronized: ^3.0.0
  test: ^1.18.2
